import { ProductPromo } from "@/types/product";

export const PromoProducts: ProductPromo[] = [
  {
    id: "1",
    name: "Miel Sauvage Bio",
    category: "Miel",
    price: 8000,
    originalPrice: 10000,
    image: "https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp",
    description: "Miel 100% naturel, récolté dans les forêts africaines.",
    ingredients: ["Miel pur"],
    benefits: ["Énergisant", "Renforce l'immunité"],
    usage: "1 cuillère par jour",
    stock: 50
  },
  {
    id: "2",
    name: "Savon Noir Africain",
    category: "Savons",
    price: 2000,
    originalPrice: 2500,
    image: "https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp",
    description: "Savon naturel pour peau douce et hydratée.",
    ingredients: ["Beurre de karité", "Huile de coco"],
    benefits: ["Nettoie", "Hydrate"],
    usage: "Usage quotidien",
    stock: 100
  },
  {
    id: "3",
    name: "Huile de Baobab",
    category: "Huiles",
    price: 10000,
    originalPrice: 12000,
    image: "https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp",
    description: "Huile naturelle pour peau et cheveux.",
    ingredients: ["Huile de Baobab"],
    benefits: ["Nourrit", "Régénère la peau"],
    usage: "Appliquer sur la peau ou cheveux",
    stock: 30
  },
  {
    id: "4",
    name: "Miel de Forêt",
    category: "Miel",
    price: 7000,
    originalPrice: 7500,
    image: "https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp",
    description: "Miel pur récolté dans la forêt.",
    ingredients: ["Miel pur"],
    benefits: ["Énergie", "Antioxydant"],
    usage: "1 cuillère par jour",
    stock: 40
  },
  {
    id: "5",
    name: "Miel de Fleurs Sauvages",
    category: "Miel",
    price: 8500,
    originalPrice: 9000,
    image: "https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp",
    description: "Miel parfumé aux fleurs sauvages.",
    ingredients: ["Miel pur"],
    benefits: ["Tonique", "Renforce la vitalité"],
    usage: "1 cuillère par jour",
    stock: 60
  },
  {
    id: "6",
    name: "Savon au Karité",
    category: "Savons",
    price: 2500,
    originalPrice: 3000,
    image: "https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp",
    description: "Savon hydratant au beurre de karité.",
    ingredients: ["Beurre de karité"],
    benefits: ["Hydrate", "Adoucit la peau"],
    usage: "Usage quotidien",
    stock: 80
  },
  {
    id: "7",
    name: "Savon à l’Argile Verte",
    category: "Savons",
    price: 2200,
    originalPrice: 2700,
    image: "https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp",
    description: "Savon purifiant à l’argile verte.",
    ingredients: ["Argile verte", "Huiles végétales"],
    benefits: ["Purifie", "Détoxifie"],
    usage: "Usage quotidien",
    stock: 70
  },
  {
    id: "8",
    name: "Huile de Coco Bio",
    category: "Huiles",
    price: 8500,
    originalPrice: 10000,
    image: "https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp",
    description: "Huile vierge de coco bio.",
    ingredients: ["Huile de coco"],
    benefits: ["Hydrate", "Nourrit cheveux & peau"],
    usage: "Appliquer selon besoin",
    stock: 45
  },
  {
    id: "9",
    name: "Huile de Ricin",
    category: "Huiles",
    price: 8000,
    originalPrice: 9500,
    image: "https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp",
    description: "Huile pour la pousse des cheveux et cils.",
    ingredients: ["Huile de ricin"],
    benefits: ["Fortifie cheveux", "Stimule pousse"],
    usage: "Appliquer sur cheveux et cils",
    stock: 35
  },
  {
    id: "0",
    name: "Huile d’Argan",
    category: "Huiles",
    price: 13000,
    originalPrice: 15000,
    image: "https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp",
    description: "Huile rare pour peau et cheveux.",
    ingredients: ["Huile d’argan"],
    benefits: ["Régénère", "Nourrit"],
    usage: "Appliquer selon besoin",
    stock: 20
  }
];
